/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "budget-tracker",
  "name": "Budget Brain",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Set my dining budget to 300 and groceries to 450",
      "does": "Updates both monthly budgets."
    },
    {
      "say": "Anything containing UBER is transport from now on",
      "does": "Adds a categorization rule and reapplies it."
    },
    {
      "say": "What did I spend the most on last month?",
      "does": "Looks up the month's category totals and answers."
    }
  ]
};
